//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.30 at 01:22:05 PM ALMT 
//


package com.epam.beans.soap.com.epam;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.epam package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Auditorium_QNAME = new QName("http://epam.com", "auditorium");
    private final static QName _Event_QNAME = new QName("http://epam.com", "event");
    private final static QName _User_QNAME = new QName("http://epam.com", "user");
    private final static QName _Rate_QNAME = new QName("http://epam.com", "rate");
    private final static QName _UserRole_QNAME = new QName("http://epam.com", "userRole");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.epam
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Auditorium }
     *
     */
    public Auditorium createAuditorium() {
        return new Auditorium();
    }

    /**
     * Create an instance of {@link Event }
     *
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link User }
     *
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link GetUserByIdRequest }
     *
     */
    public GetUserByIdRequest createGetUserByIdRequest() {
        return new GetUserByIdRequest();
    }

    /**
     * Create an instance of {@link GetUserByIdResponse }
     *
     */
    public GetUserByIdResponse createGetUserByIdResponse() {
        return new GetUserByIdResponse();
    }

    /**
     * Create an instance of {@link RegisterUserRequest }
     *
     */
    public RegisterUserRequest createRegisterUserRequest() {
        return new RegisterUserRequest();
    }

    /**
     * Create an instance of {@link RegisterUserResponse }
     *
     */
    public RegisterUserResponse createRegisterUserResponse() {
        return new RegisterUserResponse();
    }

    /**
     * Create an instance of {@link RemoveUserRequest }
     *
     */
    public RemoveUserRequest createRemoveUserRequest() {
        return new RemoveUserRequest();
    }

    /**
     * Create an instance of {@link RemoveUserResponse }
     *
     */
    public RemoveUserResponse createRemoveUserResponse() {
        return new RemoveUserResponse();
    }

    /**
     * Create an instance of {@link GetEventByIdRequest }
     *
     */
    public GetEventByIdRequest createGetEventByIdRequest() {
        return new GetEventByIdRequest();
    }

    /**
     * Create an instance of {@link GetEventByIdResponse }
     *
     */
    public GetEventByIdResponse createGetEventByIdResponse() {
        return new GetEventByIdResponse();
    }

    /**
     * Create an instance of {@link CreateEventRequest }
     *
     */
    public CreateEventRequest createCreateEventRequest() {
        return new CreateEventRequest();
    }

    /**
     * Create an instance of {@link CreateEventResponse }
     *
     */
    public CreateEventResponse createCreateEventResponse() {
        return new CreateEventResponse();
    }

    /**
     * Create an instance of {@link RemoveEventRequest }
     *
     */
    public RemoveEventRequest createRemoveEventRequest() {
        return new RemoveEventRequest();
    }

    /**
     * Create an instance of {@link RemoveEventResponse }
     *
     */
    public RemoveEventResponse createRemoveEventResponse() {
        return new RemoveEventResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Auditorium }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://epam.com", name = "auditorium")
    public JAXBElement<Auditorium> createAuditorium(Auditorium value) {
        return new JAXBElement<Auditorium>(_Auditorium_QNAME, Auditorium.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Event }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://epam.com", name = "event")
    public JAXBElement<Event> createEvent(Event value) {
        return new JAXBElement<Event>(_Event_QNAME, Event.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link User }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://epam.com", name = "user")
    public JAXBElement<User> createUser(User value) {
        return new JAXBElement<User>(_User_QNAME, User.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Rate }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://epam.com", name = "rate")
    public JAXBElement<Rate> createRate(Rate value) {
        return new JAXBElement<Rate>(_Rate_QNAME, Rate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserRole }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://epam.com", name = "userRole")
    public JAXBElement<UserRole> createUserRole(UserRole value) {
        return new JAXBElement<UserRole>(_UserRole_QNAME, UserRole.class, null, value);
    }

}
